package graphics;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.image.FilteredImageSource;
import java.awt.image.ImageFilter;
import java.awt.image.ImageProducer;
import java.awt.image.RGBImageFilter;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import student.ugal.ro.avatar22.*;
import java.awt.List;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

public class AvatarJFrameTEST extends javax.swing.JFrame {
    
    
    //declaration zone of object array and its components
    //to do -> modify for reading from files
//    Fata fata0=new Fata(0, "Rosii", 2, 350, 950);
//    Fata[] fataV={fata0};
    Fata[] fataList={new Fata(0, "alb", 2, 350, 950),
                        new Fata(1, "galben", 1, 350, 950),
                        new Fata(2, "galben", 3, 350, 950)};
Fusta fusta2= new Fusta(0, "alb",1,355,1100);
    public AvatarJFrameTEST()
    {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        showBluzaButton = new javax.swing.JButton();
        showFustaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        alegeCuloareButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        backgroundBodyLabel = new javax.swing.JLabel();
        parLabel = new javax.swing.JLabel();
        fataLabel = new javax.swing.JLabel();
        accesoriLabel = new javax.swing.JLabel();
        bluzaLabel = new javax.swing.JLabel();
        fustaLabel = new javax.swing.JLabel();
        pantaloniLabel = new javax.swing.JLabel();
        pantofiLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        showBluzaButton.setText("Show Bluza");
        showBluzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBluzaButtonActionPerformed(evt);
            }
        });

        showFustaButton.setText("Show Fusta");
        showFustaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFustaButtonActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fata nr.", "Index", "Culoare", "Nume fisier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(3).setResizable(false);
        }

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "alb", "albastru", "galben" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        alegeCuloareButton.setText("Alege culoare");
        alegeCuloareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alegeCuloareButtonActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(alegeCuloareButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showFustaButton)
                            .addComponent(showBluzaButton))
                        .addGap(44, 44, 44))))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alegeCuloareButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addComponent(showFustaButton)
                        .addGap(18, 18, 18)
                        .addComponent(showBluzaButton)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setLayout(new java.awt.CardLayout());
        jLayeredPane1.add(backgroundBodyLabel, "card2");
        ImageIcon backgroundBodyLabelImage=new ImageIcon("Resources\\Corp.png");
        backgroundBodyLabel.setIcon(backgroundBodyLabelImage);

        parLabel.setPreferredSize(new java.awt.Dimension(565, 800));
        jLayeredPane1.setLayer(parLabel, 2);
        jLayeredPane1.add(parLabel, "card5");

        fataLabel.setPreferredSize(new java.awt.Dimension(565, 800));
        jLayeredPane1.setLayer(fataLabel, 3);
        jLayeredPane1.add(fataLabel, "card6");

        accesoriLabel.setPreferredSize(new java.awt.Dimension(565, 800));
        jLayeredPane1.setLayer(accesoriLabel, 4);
        jLayeredPane1.add(accesoriLabel, "card8");

        bluzaLabel.setVisible(true);
        bluzaLabel.setPreferredSize(new java.awt.Dimension(565, 800));
        jLayeredPane1.setLayer(bluzaLabel, 5);
        jLayeredPane1.add(bluzaLabel, "card3");
        //ImageIcon bluzaLabelIcon = scaleImage("Resources\\bluza\\bluza_alb.png", 1000, 700);
        ImageIcon bluzaLabelIcon=new ImageIcon("Resources\\bluza\\bluza_alb.png");
        bluzaLabel.setIcon(bluzaLabelIcon);

        fustaLabel.setPreferredSize(new java.awt.Dimension(565, 800));
        jLayeredPane1.setLayer(fustaLabel, 6);
        jLayeredPane1.add(fustaLabel, "card4");
        //ImageIcon fustaLabelIcon = scaleImage("Resources\\fusta\\fusta_alb(1).png", 1000, 700);
        ImageIcon fustaLabelIcon=new ImageIcon("Resources\\fusta\\"+fusta2.getNumePng());
            fustaLabel.setIcon(fustaLabelIcon);

            pantaloniLabel.setPreferredSize(new java.awt.Dimension(565, 800));
            jLayeredPane1.setLayer(pantaloniLabel, 7);
            jLayeredPane1.add(pantaloniLabel, "card9");

            pantofiLabel.setPreferredSize(new java.awt.Dimension(565, 800));
            jLayeredPane1.setLayer(pantofiLabel, 8);
            jLayeredPane1.add(pantofiLabel, "card10");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents



    private void showBluzaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showBluzaButtonActionPerformed
    {//GEN-HEADEREND:event_showBluzaButtonActionPerformed
       bluzaLabel.setVisible(!bluzaLabel.isVisible());
    }//GEN-LAST:event_showBluzaButtonActionPerformed

    private void showFustaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showFustaButtonActionPerformed
    {//GEN-HEADEREND:event_showFustaButtonActionPerformed
        fustaLabel.setVisible(!fustaLabel.isVisible());
    }//GEN-LAST:event_showFustaButtonActionPerformed
int j=0;
    private void alegeCuloareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alegeCuloareButtonActionPerformed
       String filtruCuloare=jList2.getSelectedValue();
       for(int k=0;k<=j;k++)//reinitializarea tabelului (golirea)
       {
           tabel.setValueAt(null, k, 0);
           tabel.setValueAt(null, k, 1);
           tabel.setValueAt(null, k, 2);
           tabel.setValueAt(null, k, 3);
       }
           j=0;
// sfarsit golire tabel == true
     for(int i=0;i<=2;i++)
     {
         if(fataList[i].getEyeColor().equals(filtruCuloare))
         {
             tabel.setValueAt(j+1,j ,0 );
              tabel.setValueAt(fataList[i].getIndex(),j ,1 );
              tabel.setValueAt(fataList[i].getEyeColor(), j, 2);
               tabel.setValueAt(fataList[i].getNamePng(),j ,3 );
               j++;
         }
     }
    }//GEN-LAST:event_alegeCuloareButtonActionPerformed

//    public static ImageIcon scaleImage(String imagePath, int maxWidth, int maxHeight)
//    {
//        ImageReader imageReader = new ImageReader(imagePath);
//        BufferedImage image = imageReader.getImage();
//
//        double scale = Math.min((double) maxWidth / image.getWidth(), (double) maxHeight / image.getHeight());
//        int scaledWidth = (int) (image.getWidth() * scale);
//        int scaledHeight = (int) (image.getHeight() * scale);
//
//        Image scaledImage = image.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);
//        return new ImageIcon(scaledImage);
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AvatarJFrameTEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AvatarJFrameTEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AvatarJFrameTEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AvatarJFrameTEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new AvatarJFrameTEST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accesoriLabel;
    private javax.swing.JButton alegeCuloareButton;
    private javax.swing.JLabel backgroundBodyLabel;
    private javax.swing.JLabel bluzaLabel;
    private javax.swing.JLabel fataLabel;
    private javax.swing.JLabel fustaLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel pantaloniLabel;
    private javax.swing.JLabel pantofiLabel;
    private javax.swing.JLabel parLabel;
    private javax.swing.JButton showBluzaButton;
    private javax.swing.JButton showFustaButton;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
